apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 846767006554.dkr.ecr.us-east-1.amazonaws.com/mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value:"pwd"
    ports:
    - containerPort: 3306