apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees
  labels:
    app: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webapp
        image: 846767006554.dkr.ecr.us-east-1.amazonaws.com/mywebapp:v6.0
        ports:
        - containerPort: 8080
        env:
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pwd"
        - name: DBPORT
          value: "3306"
        - name: DBHOST
          value: "10.244.0.3"
        - name: APP_COLOR
          value: "green"