apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    role: webapp
spec:
  containers:
  - name: webapp
    image: 846767006554.dkr.ecr.us-east-1.amazonaws.com/mywebapp
    ports:
    - containerPort: 8080
    env:
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "pwd"
    - name: DBPORT
      value: "3306"
    - name: DBHOST
      value: "3.239.23.117"
    - name: APP_COLOR
      value: "green"
  imagePullSecrets:
  - name: regcred
